### ISSUE TITLE
module 'xdem.coreg' has no attribute 'VerticalShift'

### ISSUE THREAD

**Issue by cwywilson** [GlacioHack/xdem#448]
Hi everyone,

I'm currently facing an issue while attempting to utilize xdem's VerticalShift() function for co-registering two DEMs. The system consistently reports the following error:

AttributeError: module 'xdem.coreg' has no attribute 'VerticalShift'

Despite conducting thorough investigations, I haven't been able to resolve this problem. Below is my entire code:

vshift = xdem.coreg.VerticalShift()
vshift.fit(dem_2021, dem_1960, inlier_mask=inlier_mask)
shifted_dem = vshift.apply(dem_1960)
vshift_median = xdem.coreg.VerticalShift(vshift_func=np.median)

I would greatly appreciate any insights or suggestions on how to address this issue. Thank you in advance for your help!

Best regards,
Wilson

**Comment by rhugonnet** [comment]
Thanks for opening this issue @cwywilson. Can you also:
- Add your full code (import statements) into a minimal reproducible example,
- xDEM version.

Locally and in all tests (Linux, MacOS, Windows), the following works with xDEM 0.0.16 (current version):
```python
import xdem
vshift = xdem.coreg.VerticalShift()
```
So it's hard to pinpoint why you would have this issue :thinking:

**Comment by cwywilson** [comment]
Thanks for helping.  I am using xDEM Version: 0.0.13
I try to update xDEM to 0.0.16 with

`pip install --upgrade xdem`

But, the system still keep me in 0.0.13. May I ask how can I do so?

Here is the code :

```
import geoutils as gu
import matplotlib.pyplot as plt
import numpy as np
import xdem
from xdem import coreg

dem_2020 = xdem.DEM("D:\BICdata\ArcticDEMclip.tif")
dem_1960 = xdem.DEM("D:\BICdata\BICDEMrwithice.tif").reproject(dem_2020)

outlines_2000 = gu.Vector("D:\CODEM\Shapefile\RGI2000-v7.0-G-04_arctic_canada_south\RGI2000-v7.0-G-04_arctic_canada_south.shp")
inlier_mask = outlines_2000.create_mask(dem_2020)

vshift = xdem.coreg.VerticalShift()
vshift.fit(dem_2020, dem_1960, inlier_mask=inlier_mask)

shifted_dem = vshift.apply(dem_1960)
vshift_median = xdem.coreg.VerticalShift(vshift_func=np.median)


ddem_pre = dem_1960 - dem_2020
ddem_post = shifted_dem - dem2020
plt.figure(figsize=(50, 50))
ddem_pre.show(cmap='coolwarm_r', vmin=-100, vmax=100, cb_title="Elevation change (m)")
ddem_post.show(cmap='coolwarm_r', vmin=-100, vmax=100, cb_title="Elevation change (m)")

```

Thanks for helps indeed

**Comment by rhugonnet** [comment]
Here's the info to install/update your package: https://xdem.readthedocs.io/en/stable/how_to_install.html#installing-with-mamba-recommended. We recommend using `mamba`. You can force a package version by doing:
`pip install xdem==0.0.16` or `mamba install xdem==0.0.16`.

**Comment by cwywilson** [comment]
Hi, Thanks for helping. End up, I re-installed the entire system to get 0.0.16 . Now, everything works well. Thanks for making xDEM

**Comment by rhugonnet** [comment]
Perfect! Note that there is a bug with coregistration pipelines in `0.0.16`: https://github.com/GlacioHack/xdem/issues/447. In the meantime, you can use coregistration steps one by one, without using a pipeline. We'll try to fix those soon.
